apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: foodfacts
spec:
  selector:
    app: mysql
  ports:
    - port: 3306
      targetPort: 3306
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: foodfacts
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: app-secrets
                key: MYSQL_ROOT_PASSWORD
          - name: MYSQL_DATABASE
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: MYSQL_DATABASE
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                name: app-secrets
                key: MYSQL_USER
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: app-secrets
                key: MYSQL_PASSWORD
          - name: FILE_NAME
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: FILE_NAME
          - name: SELECTED_COLUMNS
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: SELECTED_COLUMNS
        readinessProbe:
          exec:
            command:
              - sh
              - -c
              - "mysqladmin ping -uroot -p\"$MYSQL_ROOT_PASSWORD\""
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: data-volume
          mountPath: /var/lib/mysql-files
      volumes:
      - name: data-volume
        hostPath:
          path: /host_mnt/Users/anmilka/mlops/MLOps-lab8/data
          type: Directory
---
# Spark Master Service
apiVersion: v1
kind: Service
metadata:
  name: spark-master
  namespace: foodfacts
spec:
  selector:
    app: spark-master
  ports:
    - name: spark
      port: 7077
      targetPort: 7077
    - name: webui
      port: 8080
      targetPort: 8080
---
# Spark Master Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-master
  namespace: foodfacts
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark-master
  template:
    metadata:
      labels:
        app: spark-master
    spec:
      containers:
      - name: spark-master
        image: bitnami/spark:3.5.1
        env:
          - name: SPARK_MODE
            value: master
          - name: SPARK_DAEMON_MEMORY
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: SPARK_DAEMON_MEMORY
          - name: SPARK_DRIVER_MEMORY
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: SPARK_DRIVER_MEMORY
          - name: SPARK_MASTER_PORT
            value: "7077"
          - name: SPARK_MASTER_WEBUI_PORT
            value: "8080"
          - name: SPARK_LOCAL_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
        ports:
        - containerPort: 7077
        - containerPort: 8080
---
# Spark Worker Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-worker
  namespace: foodfacts
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark-worker
  template:
    metadata:
      labels:
        app: spark-worker
    spec:
      containers:
      - name: spark-worker
        image: bitnami/spark:3.5.1
        env:
          - name: SPARK_MODE
            value: worker
          - name: SPARK_MASTER_URL
            value: spark://spark-master:7077
          - name: SPARK_WORKER_CORES
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: SPARK_WORKER_CORES
          - name: SPARK_WORKER_MEMORY
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: SPARK_WORKER_MEMORY
          - name: SPARK_DAEMON_MEMORY
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: SPARK_DAEMON_MEMORY
          - name: SPARK_LOG_LEVEL
            value: "DEBUG"


